{-# OPTIONS -fno-warn-incomplete-patterns #-}
module PrintTom where

-- pretty-printer generated by the BNF converter

import AbsTom
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: [a] -> Doc
  prtList = concatD . map (prt 0)

instance Print a => Print [a] where
  prt _ = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))



instance Print Type where
  prt i e = case e of
   TInt  -> prPrec i 1 (concatD [doc (showString "int")])
   TBool  -> prPrec i 1 (concatD [doc (showString "bool")])


instance Print BExp where
  prt i e = case e of
   BTrue  -> prPrec i 0 (concatD [doc (showString "true")])
   BFalse  -> prPrec i 0 (concatD [doc (showString "false")])


instance Print Exp where
  prt i e = case e of
   EOr exp0 exp -> prPrec i 0 (concatD [prt 0 exp0 , doc (showString "||") , prt 1 exp])
   EAnd exp0 exp -> prPrec i 1 (concatD [prt 1 exp0 , doc (showString "&&") , prt 2 exp])
   EEq exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "==") , prt 3 exp])
   ENeq exp0 exp -> prPrec i 2 (concatD [prt 2 exp0 , doc (showString "!=") , prt 3 exp])
   ELt exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "<") , prt 4 exp])
   EGt exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString ">") , prt 4 exp])
   ELte exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString "<=") , prt 4 exp])
   EGte exp0 exp -> prPrec i 3 (concatD [prt 3 exp0 , doc (showString ">=") , prt 4 exp])
   EAdd exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "+") , prt 5 exp])
   ESub exp0 exp -> prPrec i 4 (concatD [prt 4 exp0 , doc (showString "-") , prt 5 exp])
   EMul exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "*") , prt 6 exp])
   EDiv exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "/") , prt 6 exp])
   EMod exp0 exp -> prPrec i 5 (concatD [prt 5 exp0 , doc (showString "%") , prt 6 exp])
   ENeg exp -> prPrec i 6 (concatD [doc (showString "-") , prt 6 exp])
   ENot exp -> prPrec i 6 (concatD [doc (showString "!") , prt 6 exp])
   ECall id exps -> prPrec i 7 (concatD [prt 0 id , doc (showString "(") , prt 0 exps , doc (showString ")")])
   EVar id -> prPrec i 8 (concatD [prt 0 id])
   EInt n -> prPrec i 8 (concatD [prt 0 n])
   EBool bexp -> prPrec i 8 (concatD [prt 0 bexp])
   EIver exp -> prPrec i 8 (concatD [doc (showString "[") , prt 0 exp , doc (showString "]")])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])

instance Print Decl where
  prt i e = case e of
   Decl id type' -> prPrec i 0 (concatD [doc (showString "var") , prt 0 id , doc (showString ":") , prt 0 type'])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , doc (showString ".") , prt 0 xs])

instance Print Lvalue where
  prt i e = case e of
   LIdent id -> prPrec i 0 (concatD [prt 0 id])


instance Print Stm where
  prt i e = case e of
   SBlock decls fundefs stms -> prPrec i 0 (concatD [doc (showString "{") , prt 0 decls , prt 0 fundefs , prt 0 stms , doc (showString "}")])
   SExp exp -> prPrec i 0 (concatD [prt 0 exp , doc (showString ";")])
   SWhile exp stm -> prPrec i 0 (concatD [doc (showString "while") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SReturn exp -> prPrec i 0 (concatD [doc (showString "return") , prt 0 exp , doc (showString ";")])
   SAssign lvalue exp -> prPrec i 0 (concatD [prt 0 lvalue , doc (showString "=") , prt 0 exp , doc (showString ";")])
   SPrint exp -> prPrec i 0 (concatD [doc (showString "print") , prt 0 exp , doc (showString ";")])
   SIf exp stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm])
   SIfElse exp stm0 stm -> prPrec i 0 (concatD [doc (showString "if") , doc (showString "(") , prt 0 exp , doc (showString ")") , prt 0 stm0 , doc (showString "else") , prt 0 stm])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print FunDef where
  prt i e = case e of
   FunDef id params type' stm -> prPrec i 0 (concatD [doc (showString "fun") , prt 0 id , doc (showString "(") , prt 0 params , doc (showString ")") , doc (showString "->") , prt 0 type' , prt 0 stm])

  prtList es = case es of
   [] -> (concatD [])
   x:xs -> (concatD [prt 0 x , prt 0 xs])

instance Print Param where
  prt i e = case e of
   PVar id type' -> prPrec i 0 (concatD [doc (showString "var") , prt 0 id , doc (showString ":") , prt 0 type'])
   PRef id type' -> prPrec i 0 (concatD [doc (showString "ref") , prt 0 id , doc (showString ":") , prt 0 type'])

  prtList es = case es of
   [] -> (concatD [])
   [x] -> (concatD [prt 0 x])
   x:xs -> (concatD [prt 0 x , doc (showString ",") , prt 0 xs])


